document.getElementById("myH1").textContent = 
"WEEK 5 ASSIGNMENT";

document.getElementById("myP").textContent = 
"I have recently started learning HTML and CSS, and it's been an exciting journey into the world of web development. As I go through the basics, I am beginning to understand how websites are created and styled from the ground up. I am learning how to use elements like headings, paragraphs, lists, images, and links to organize content in a meaningful way. It's fascinating to see how everything fits together to form the layout of a site. CSS is helping me understand how to add design and visual appeal. I've started learning how to change colors, adjust fonts, manage spacing, and even create simple layouts. It's interesting to see how styling can completely transform a plain HTML page. Even though I am still in the early stages, this introduction has sparked a strong interest in web design. I'm looking forward to applying what I learn in small projects and gradually building more complex and responsive websites.";

document.getElementById("myP1").textContent = 
"As I progress with my learning, I'm beginning to see how HTML and CSS work hand in hand. HTML gives structure to a webpage, while CSS enhances its appearance and user experience. I'm especially enjoying experimenting with different CSS properties like background colors, borders, font styles, and layout techniques such as Flexbox. I've also started to appreciate the importance of writing clean, organized code. Proper indentation, naming conventions, and commenting make it easier to understand and update my work later on. I'm currently practicing by creating simple web pages like personal profiles and basic landing pages to apply what I've learned. Although I'm still building my confidence, each lesson brings more clarity and excitement. I'm motivated to keep learning and eventually explore JavaScript and other front-end tools that can help me create interactive and dynamic websites. This journey has just begun, but it's already showing me the creative possibilities in tech.";


